
server:
  port: 8888
spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  application:
    name: nacos-consumer
management:
  endpoints:
    web:
      exposure:
        include: "*"