server:
  port: 2003

spring:
  application:
    name: seata-account-service
  cloud:
    alibaba:
      seata:
        tx-service-group: springcloud-seata
    nacos:
      discovery:
        server-addr: 192.168.10.100:8848
        ip: 192.168.10.100
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.10.100:3306/seata_account?serverTimezone=UTC
    username: leellun
    password: liulun666
  aop:
    auto: true
    proxy-target-class: true
feign:
  hystrix:
    enabled: false
logging:
  level:
    io:
      seata: info

mybatis:
  mapperLocations: classpath:mapper/*.xml
seata:
  service:
    grouplist:
      default: 192.168.10.103:8091