server:
  port: 2001

spring:
  application:
    name: seata-order-service
  cloud:
    alibaba:
      seata:
        #自定义事务组名称需要与seata-server中的对应
        tx-service-group: springcloud-seata
    nacos:
      discovery:
        server-addr: 192.168.10.100:8848
        ip: 192.168.10.100
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.10.100:3306/seata_order?serverTimezone=UTC
    username: leellun
    password: liulun666
  aop:
    auto: true
    proxy-target-class: true
feign:
  hystrix:
    enabled: false

logging:
  level:
    io:
      seata: info

mybatis:
  mapperLocations: classpath:mapper/*.xml

seata:
  service:
    grouplist:
      defaultZone: 192.168.10.103:8091