server:
  port: 8308

spring:
  application:
    name: spring-cloud-sentinel
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.10.100:8848
        ip: 192.168.10.100
    sentinel:
      transport:
        dashboard: 192.168.10.100:8080
        port: 8719
        client-ip: 192.168.10.100

management:
  endpoints:
    web:
      exposure:
        include: "*"
