
server:
  port: 8099
spring:
  application:
    name: rabbitmq-provider
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    stream:
      binders: # 在此处配置要绑定的rabbitmq的服务信息；
        defaultRabbit: # 表示定义的名称，用于于binding整合
          environment: # 设置rabbitmq的相关的环境配置
            spring:
              rabbitmq:
                host: 192.168.10.103
                port: 5672
                username: leellun
                password: liulun666
          type: rabbit # 消息组件类型
      bindings: # 服务的整合处理
        output: # 这个名字是一个通道的名称
          binder: defaultRabbit # 表示要使用的Exchange名称定义
          content-type: application/json # 设置消息类型，本次为json，文本则设置“text/plain”
          destination: studyExchange # 设置要绑定的消息服务的具体设置
